#PARA UTILIZAR ESSES ENDPOINTS É NECESSÁRIO INSTALAR A EXTENSÃO DO VSCODE "REST CLIENT"
###

GET http://localhost:3333/cantor

###

POST http://localhost:3333/cantor
Content-Type: application/json

{
    
    "nome": "caio",
    "shows": "43",
    "idade": "18"
}

###

PUT http://localhost:3333/cantor/70413209-c762-401b-b87a-7247456955f6
Content-Type: application/json

{
    "nome": "caio",
    "shows": "43",
    "idade": "22"
}

###

DELETE http://localhost:3333/cantor/id
